[package]
name = "event_manager"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html


[[target.starknet-contract]]

[dependencies]
starknet = "2.8.0"

[dev-dependencies]
cairo_test = "2.8.0"
